apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: loki-pv
  resources:
    requests:
      storage: 1Gi