apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: prometheus-pv-v1
  resources:
    requests:
      storage: 1Gi