dags:
  persistence:
    enabled: false # (1)

  gitSync:
    enabled: true
    repo: "git@github.com:nsalexamy/airflow-dags-example.git" # (2)
    branch: "main"
    rev: HEAD
    depth: 1
    wait: 60  # Sync every 60 seconds
    subPath: "dags" # (3)
    containerName: "git-sync"

    sshKeySecret: "airflow-git-ssh-key-secret" # (4)
    #(5)
    knownHosts: |
      github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhL...++Tpockg=
      github.com ssh-rsa AAAAB3NzaC1yc2...+p1vN1/wsjk=
redis:
  enabled: false  # Celery backend not needed for KubernetesExecutor

postgresql:
  enabled: true

  image:
    #registry:
    repository: bitnamilegacy/postgresql
    tag: 16.1.0-debian-11-r15 # 16.1.0-debian-11-r15 is default. 17.6.0-debian-12-r4

  auth:
    enablePostgresUser: true
    username: "airflowuser"
    existingSecret: airflow-postgresql-credentials

ingress:
  enabled: true
  web:
    enabled: true
    host: "airflow.nsa2.com"
    ingressClassName: "traefik"

triggerer:
  replicas: 2
  persistence:
    size: 1Gi